package com.sumadhura.employeeservice.enums;

public interface NotificationsSqlQuery {
	public static final String STATUS_ID ="STATUS_ID";
	public static final String SITE_ID ="SITE_ID";
	public static final String WHERE =" WHERE ";
	
	public static final String SELECT =" SELECT ";
	public static final String DISTINCT =" DISTINCT ";
	
	
	public static final String AND =" AND ";
	public static final String SITE_STATUS_COND =" SITE.STATUS_ID = :STATUS_ID ";
	public static final String FLOOR_DET_STATUS_ID_COND =" FLOORD.STATUS_ID = :STATUS_ID ";
	public static final String SITE_ID_IN_COND =" SITE.SITE_ID IN(:SITE_ID) ";
	public static final String STATE_ID_IN_COND =" SITE.STATE_ID IN(:STATE_ID) ";
	public static final String FLAT_ID_IN_COND =" FLAT.FLAT_ID IN(:FLAT_ID) ";
	
	public static final String SITE_DD_COL=" SITE.SITE_ID AS ID ,SITE.NAME AS NAME ";
	//public static final String BLOCK_DD_COL=" BLOCK.BLOCK_ID AS ID ,BLOCK.NAME AS NAME,BLOCKD.BLOCK_DET_ID AS DETID,SITE.SITE_ID ";
	public static final String BLOCK_DD_COL=" BLOCK.BLOCK_ID AS ID ,CONCAT(CONCAT(SITE.SHORT_FORM,'-'),BLOCK.NAME) AS NAME,BLOCKD.BLOCK_DET_ID AS DETID,SITE.SITE_ID ";
	
	//public static final String FLOOR_DD_COL=" FLOOR.FLOOR_ID AS ID ,FLOOR.NAME AS NAME,FLOORD.FLOOR_DET_ID AS DETID,BLOCKD.BLOCK_DET_ID AS MAPID ";
	public static final String FLOOR_DD_COL=" FLOOR.FLOOR_ID AS ID , CONCAT(CONCAT(CONCAT(CONCAT(SITE.SHORT_FORM,'-'),BLOCK.NAME),'-'),FLOOR.NAME) AS NAME,FLOORD.FLOOR_DET_ID AS DETID,BLOCKD.BLOCK_DET_ID AS MAPID ";
	
	
	
	//public static final String FLAT_DD_COL=" FLAT.FLAT_ID AS ID ,FLAT.FLAT_NO AS NAME,FLATD.FLAT_DET_ID AS DETID,FLOORD.FLOOR_DET_ID AS MAPID ";
	public static final String FLAT_DD_COL=" FLAT.FLAT_ID AS ID ,CONCAT(CONCAT(CONCAT(CONCAT(SITE.SHORT_FORM,'-'),BLOCK.NAME),'-'),FLAT.FLAT_NO) AS NAME,FLATD.FLAT_DET_ID AS DETID,FLOORD.FLOOR_DET_ID AS MAPID ";
	
	
	public static final String FLAT_DEVICE_COL=" SITE.SITE_ID,BLOCKD.BLOCK_DET_ID,FLOORD.FLOOR_DET_ID,FLAT.FLAT_ID ";
	public static final String DEVICE_IS_NOT_NULL=" DEVICE.DEVICE_TOKEN IS NOT NULL ";
	public static final String FLAT_COUNT=" count(distinct FLAT.FLAT_ID) ";
	public static final String FLAT_DETAILS2=" FLAT.FLAT_ID,FLAT.FLAT_NO ";
	
	
	public static final String ACTIVE_SITE_BLCOK_FLOOR_FLAT=" FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID AND SITE.STATUS_ID=2 AND BLOCKD.STATUS_ID=6)"
					+" JOIN BLOCK BLOCK ON(BLOCKD.BLOCK_ID=BLOCK.BLOCK_ID) JOIN FLOOR_DETAILS FLOORD JOIN FLOOR FLOOR ON(FLOORD.FLOOR_ID=FLOOR.FLOOR_ID)"
					+" ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID AND FLOORD.STATUS_ID=6 ) JOIN FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID AND FLATD.STATUS_ID=6)"
					+" JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID) JOIN FLAT_BOOKING FLATB ON(FLATB.FLAT_ID=FLATD.FLAT_ID AND FLATB.STATUS_ID=6) JOIN"
					+" APP_REGISTRATION APPR ON(FLATB.CUST_ID=APPR.CUST_ID AND APPR.STATUS_ID=6) JOIN DEVICE DEVICE ON(APPR.DEVICE_ID=DEVICE.DEVICE_ID AND DEVICE.STATUS_ID=6) ";
	
	public static final String GET_ACTIVE_SITE_WITH_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(SITE_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	
	public static final String GET_ACTIVE_BLOCK_WITH_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(BLOCK_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	
	public static final String GET_ACTIVE_FLOOR_WITH_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(FLOOR_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	
	public static final String GET_ACTIVE_FLAT_WITH_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(FLAT_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	
	public static final String ACTIVE_FLAT_DEVICE_TOKEN=new StringBuilder(SELECT).append(DISTINCT).append(FLAT_DEVICE_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	public static final String GET_ACTIVE_FLAT_COUNT=new StringBuilder(SELECT).append(FLAT_COUNT)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	public static final String GET_ACTIVE_FLATS=new StringBuilder(SELECT).append(DISTINCT).append(FLAT_DETAILS2)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	
	/* QRY_TO_GET_SERIES_SBUA_FACING_BHK_TYPE_WITH_APP_REG_NOTIFICATION
	public static final String QRY_TO_GET_SERIES_SBUA_FACING_BHK_TYPE_WITH_APP_REG = new StringBuilder(" SELECT FLATD.FLAT_DET_ID AS FLAT_DET_ID, ")
			.append(" FLAT.FLAT_NO AS FLAT_NO, FLATD.SBUA AS SBUA, FLATD.FACING AS FACING, FLATD.BHK AS BHK_TYPE ")
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT)
			.toString(); */
	
	/* QRY_TO_GET_SBUA_WITH_APP_REG_NOTIFICATION*/
	public static final String QRY_TO_GET_SBUA_WITH_APP_REG = new StringBuilder(" SELECT DISTINCT FLATD.SBUA AS SBUA ")
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT)
			.toString();
	
	/* QRY_TO_GET_SERIES_WITH_APP_REG_NOTIFICATION*/
	public static final String QRY_TO_GET_SERIES_WITH_APP_REG = new StringBuilder(" SELECT DISTINCT SUBSTR(FLAT.FLAT_NO, -2) AS FLAT_SERIES ")
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT)
			.toString();
	
	/* QRY_TO_GET_FACING_WITH_APP_REG_NOTIFICATION*/
	public static final String QRY_TO_GET_FACING_WITH_APP_REG = new StringBuilder(" SELECT DISTINCT FLATD.FACING AS FACING ")
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT)
			.toString(); 
	
	/* QRY_TO_GET_BHK_TYPE_WITH_APP_REG_NOTIFICATION*/
	public static final String QRY_TO_GET_BHK_TYPE_WITH_APP_REG = new StringBuilder(" SELECT DISTINCT FLATD.BHK AS BHK_TYPE ")
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT)
			.toString();
	
	
	public static final String FLAT_ID_DD_COL=" FLAT.FLAT_ID AS SITE_ID,CONCAT(CONCAT(CONCAT(CONCAT(SITE.SHORT_FORM,'-'),BLOCK.NAME),'-'),FLAT.FLAT_NO) AS NAME,FLATD.FLAT_DET_ID AS DETID,FLOORD.FLOOR_DET_ID AS MAPID ";
	
	/* QRY_TO_GET_ACTIVE_FLATS_WITH_APP_REG_NOTIFICATION*/
	public static final String GET_ACTIVE_FLAT_ID_WITH_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(FLAT_ID_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	
	/*
	public static final String INSERT_NOTIFICATION = new StringBuilder("INSERT INTO NOTIFICATION(ID,MESSAGE,DESCRIPTION,IMAGELOCATION,CREATED_DATE,CREATED_BY,STATUS_ID)")
	.append("VALUES(notification_seq.nextval,:MESSAGE,:DESCRIPTION,:IMAGELOCATION,:CREATED_DATE,:CREATED_BY,:STATUS_ID)")
	.toString();*/
	

	public static final String INSERT_NOTIFICATION = new StringBuilder("INSERT INTO NOTIFICATION(ID,MESSAGE,DESCRIPTION,IMAGELOCATION,CREATED_DATE,CREATED_BY,STATUS_ID,FILELOCATION,NOTIFICATIONTEXT,OS_TYPE,NOTIFICATION_TYPE,NOTIFICATION_SENT_DATE_TIME)")
	.append("VALUES(notification_seq.nextval,:MESSAGE,:DESCRIPTION,:IMAGELOCATION,:CREATED_DATE,:CREATED_BY,:STATUS_ID,:FILELOCATION,:NOTIFICATIONTEXT,:OS_TYPE,:NOTIFICATION_TYPE,SYSDATE)")
	.toString();
	
	public static final String INSERT_NOTIFICATION_APPROVAL = new StringBuilder("INSERT INTO NOTIFICATION_APPROVAL(NOTIFICATION_APPROVAL_ID,APPROVAL_LEVEL,STATUS,NOTIFICATION_ID)")
			.append("VALUES(NOTIFICATION_APPROVAL_SEQ.nextval,:APPROVAL_STATUS,:STATUS,:NOTIFICATION_ID)")
			.toString();

	public static final String UPDATE_NOTIFICATION = new StringBuilder("UPDATE NOTIFICATION ")
	.append("SET MESSAGE=:MESSAGE,DESCRIPTION=:DESCRIPTION,IMAGELOCATION=:IMAGELOCATION,MODIFIED_DATE=:MODIFIED_DATE,MODIFIED_BY=:MODIFIED_BY,STATUS_ID=:STATUS_ID,FILELOCATION=:FILELOCATION,NOTIFICATIONTEXT=:NOTIFICATIONTEXT,OS_TYPE=:OS_TYPE,NOTIFICATION_SENT_DATE_TIME=SYSDATE")
	.append(" WHERE ")
	.append(" ID=:NOTIFICATION_ID ")
	.toString();
	
	public static final String UPDATE_NOTIFICATION_APPROVAL = new StringBuilder("UPDATE NOTIFICATION_APPROVAL ")
			.append("SET STATUS=:STATUS")
			.append(" WHERE ")
			.append(" NOTIFICATION_ID=:NOTIFICATION_ID AND APPROVAL_LEVEL=:APPROVAL_STATUS ")
			.toString();
	
	public static final String GET_NOTIFICATIONS =new StringBuilder("SELECT ID,MESSAGE,DESCRIPTION,IMAGELOCATION,STATUS_ID FROM NOTIFICATION ")
	.toString();
	
	public static final String GET_NOTIFICATIONS_DETAILS =new StringBuilder("SELECT NOTIFICATION_ID,SEND_TO,SEND_TYPE,STATUS FROM NOTIFICATION_DETAILS ")
	.toString();
	

	public static final String DETAIL_NOTIFICATION = new StringBuilder("SELECT DISTINCT SITE.SITE_ID,BD.BLOCK_DET_ID,FD.FLOOR_DET_ID,FLAT.FLAT_ID FROM ")
	.append("SITE SITE JOIN BLOCK_DETAILS BD ON(SITE.SITE_ID=BD.SITE_ID)")
	.append("JOIN FLOOR_DETAILS FD ON(BD.BLOCK_DET_ID=FD.BLOCK_DET_ID) JOIN FLAT_DETAILS FLAT ON(FLAT.FLOOR_DET_ID=FD.FLOOR_DET_ID)").toString();
	
	public static final String DEVICE_DETAILS_NOTIFICATION = new StringBuilder("SELECT DISTINCT D.DEVICE_TOKEN,FLAT.FLAT_ID,D.OS_TYPE,D.UUID,D.DEVICE_ID FROM FLAT FLAT JOIN FLAT_BOOKING FLATB ON(FLAT.FLAT_ID=FLATB.FLAT_ID) JOIN ")
	.append("APP_REGISTRATION AR ON(AR.CUST_ID=FLATB.CUST_ID) JOIN DEVICE D ON(D.DEVICE_ID=AR.DEVICE_ID) ")
	.toString();
	
	public static final String INSERT_NOTIFICATION_DETAILS = new StringBuilder("INSERT INTO NOTIFICATION_DETAILS(NOTIFICATION_DETAILS_ID,SEND_TO,SEND_TYPE,NOTIFICATION_ID,STATUS,CREATED_BY) ")
	.append("VALUES(NOTIFICATION_DETAILS_SEQ.nextval,:SEND_TO,:SEND_TYPE,:NOTIFICATION_ID,:STATUS,:CREATED_BY)")
	.toString();
	
	public static final String NON_CUSTOMER_DEVICE_ID = new StringBuilder(" SELECT ")
			.append("DE.DEVICE_ID AS DEVICE_ID, ")              
			.append("DE.DEVICE_TOKEN AS DEVICE_TOKEN, ")        
			.append("DE.DEVICE_MODEL AS DEVICE_MODEL,")         
			.append("DE.APP_VERSION AS APP_VERSION, ")          
			.append("DE.OS_TYPE AS OS_TYPE, ")                  
			.append("DE.OS_VERSION AS OS_VERSION, " )          
			.append("DE.IMEI_NO AS IMEI_NO, ")                  
			.append("DE.DEVICE_STATUS AS DEVICE_STATUS, ")      
			.append("DE.USER_AGENT AS USER_AGENT, ")            
			.append("DE.USER_XID AS USER_XID, ")                
			.append("DE.UUID AS UUID, ")                       
			.append("DE.SERIAL_NO AS SERIAL_NO, ")              
			.append("DE.CREATED_DATE AS CREATED_DATE, ")        
			.append("DE.MODIFIED_DATE AS MODIFIED_DATE, ") 
			.append("DE.STATUS_ID AS STATUS_ID ")
			.append("FROM NON_CUSTOMER NC ")
			.append("INNER JOIN DEVICE DE ")
			.append("ON DE.DEVICE_ID =  NC.DEVICE_ID AND DE.STATUS_ID = :STATUS_ID AND DE.OS_TYPE IN (:OS_TYPE) ")
			.append("WHERE  NC.DEVICE_ID  NOT IN(SELECT DEVICE_ID FROM APP_REGISTRATION ) ORDER BY NC.DEVICE_ID DESC ")
			.toString();
	
	public static final String QRY_TO_GET_BLCOK_DETAILS_BY_SITE_ID = new StringBuilder(" SELECT")
	.append("  BLOCK.BLOCK_ID AS BLOCK_ID, ")
	.append("  BLOCK.NAME AS NAME, ")
	.append("  BD.BLOCK_DET_ID AS BLOCK_DET_ID, ")
	.append("  BD.SITE_ID AS SITE_ID ")
	.append("  FROM BLOCK BLOCK ")
	.append("  INNER JOIN ")
	.append("  BLOCK_DETAILS BD")
	.append("  ON(BD.BLOCK_ID=BLOCK.BLOCK_ID) ")
	.toString();

	public static final String QRY_TO_GET_FLOOR_DETAILS_BY_BLOCK_IDS = new StringBuilder(" SELECT")
	.append("  FLOOR.FLOOR_ID AS FLOOR_ID, ")
	.append("  FLOOR.NAME AS NAME, ")
	.append("  FD.FLOOR_DET_ID AS FLOOR_DET_ID, ")
	.append("  FD.BLOCK_DET_ID AS BLOCK ")
	.append("  FROM FLOOR FLOOR ")
	.append("  INNER JOIN ")
	.append("  FLOOR_DETAILS FD")
	.append("  ON(FD.FLOOR_ID=FLOOR.FLOOR_ID) ")
	.toString();
	
	public static final String QRY_TO_GET_FLOOR_DETAILS_BY_SITE_IDS = new StringBuilder(" SELECT FLOOR.FLOOR_ID,FLOOR.NAME,FLOORD.FLOOR_DET_ID,SITE.SITE_ID FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID) JOIN FLOOR_DETAILS FLOORD ")
	.append("  ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID) JOIN FLOOR FLOOR ON(FLOORD.FLOOR_ID=FLOOR.FLOOR_ID) ")	
	.toString();
	
	public static final String QRY_TO_GET_FLAT_DETAILS_BY_FLOOR_IDS = new StringBuilder(" SELECT DISTINCT")
	.append("  FLAT.FLAT_ID AS FLAT_ID, ")
	.append("  FLAT.FLAT_NO AS FLAT_NO, ")
	.append("  FD.FLAT_DET_ID AS FLAT_DET_ID, ")
	.append("  FD.FLOOR_DET_ID AS FLOOR_DET_ID ")
	.append("  FROM FLAT FLAT ")
	.append("  INNER JOIN ")
	.append("  FLAT_DETAILS FD")
	.append("  ON(FD.FLAT_ID=FLAT.FLAT_ID) JOIN FLAT_BOOKING FLATB ON(FD.FLAT_ID=FLATB.FLAT_ID) JOIN APP_REGISTRATION APPR ON(FLATB.CUST_ID=APPR.CUST_ID) JOIN DEVICE D ON(APPR.DEVICE_ID=D.DEVICE_ID) ")
	.toString();
	/*
	public static final String QRY_TO_GET_FLAT_DETAILS_BY_SITE_IDS = new StringBuilder(" SELECT FLAT.FLAT_ID,FLAT.FLAT_NO,FLATD.FLOOR_DET_ID,SITE.SITE_ID FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ")
	.append("  ON(SITE.SITE_ID=BLOCKD.SITE_ID) JOIN FLOOR_DETAILS FLOORD ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID) JOIN ")
	.append("  FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID) JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID) ")
	.toString();*/
	

	public static final String QRY_TO_GET_FLAT_DETAILS_BY_SITE_IDS = new StringBuilder(" SELECT FLAT.FLAT_ID,FLAT.FLAT_NO,FLATD.FLOOR_DET_ID,SITE.SITE_ID FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ")
	.append("  ON(SITE.SITE_ID=BLOCKD.SITE_ID) JOIN FLOOR_DETAILS FLOORD ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID) JOIN ")
	.append("  FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID) JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID) JOIN FLAT_BOOKING FLATB ON(FLATD.FLAT_ID=FLATB.FLAT_ID) JOIN APP_REGISTRATION APPR ON(FLATB.CUST_ID=APPR.CUST_ID) JOIN DEVICE D ON(APPR.DEVICE_ID=D.DEVICE_ID)")
	.toString();
	
	
/* QRY_TO_GET_SITE_DETAILS FROM SITE */
public static final String STATUS_COND_CHECK = new StringBuilder(" WHERE ")
	.append(" BD.STATUS_ID = :STATUS_ID ")
	.toString();

public static final String FLOR_STATUS_COND_CHECK = new StringBuilder(" WHERE ")
.append(" FD.STATUS_ID = :STATUS_ID ")
.toString();

public static final String SITE_IN_LIST = new StringBuilder("")
.append(" BD.SITE_ID IN(:SITE_ID) ")
.toString();

public static final String BLOCK_IN_LIST = new StringBuilder("")
.append(" FD.BLOCK_DET_ID IN(:BLOCK_DET_ID) ")
.toString();

public static final String FLOOR_IN_LIST = new StringBuilder("")
.append(" FD.FLOOR_DET_ID IN(:FLOOR_DET_ID) ")
.toString();

public static final String FLAT_IN_LIST = new StringBuilder("")
.append(" FLAT.FLAT_ID IN(:FLAT_ID) ")
.toString();

public static final String NOTIFICATION_SENT_DETAILS=new StringBuilder("INSERT INTO NOTIFICATION_SENT_DETAILS(FLAT_ID,NOTIFICATION_ID,STATUS_ID,DELIVERED_TIME,OS_TYPE,DEVICE_ID) ")
.append(" VALUES(:FLAT_ID,:NOTIFICATION_ID,:STATUS_ID,SYSDATE,:OS_TYPE,:DEVICE_ID) ").toString();


public static final String NONCUST_NOTIFICATION_SENT_DETAILS = new StringBuilder(" INSERT INTO NONCUST_NOTIFICATION_SENT_DET ")
		.append(" ( ")
		.append("  ID,")
		.append("  DEVICE_ID,")
		.append("  NOTIFICATION_ID,")
		.append("  IS_VIEWED,")
		.append("  STATUS_ID,")
		.append("  CREATED_DATE,")
		.append("  MODIFIED_DATE ")
		.append(" ) ")
		.append(" VALUES ")
		.append(" ( ")
		.append(" NONCUST_NOTIFICATION_SENT_DET_SEQ.nextval,")
		.append(":DEVICE_ID,")
		.append(":NOTIFICATION_ID,")
		.append(":IS_VIEWED,")
		.append(":STATUS_ID,")
		.append("SYSTIMESTAMP,")
		.append(":MODIFIED_DATE")
		.append(" ) ")
		.toString();

	
public static final String GET_CUSTOMER_NOTIFICATION_LIST="SELECT DISTINCT NOTIFY.ID,NOTIFY.MESSAGE,NOTIFY_SENT_DET.FLAT_ID FROM APP_REGISTRATION APPR JOIN FLAT_BOOKING FLATBOOK ON(FLATBOOK.CUST_ID=APPR.CUST_ID)"+
" JOIN NOTIFICATION_SENT_DETAILS NOTIFY_SENT_DET ON (NOTIFY_SENT_DET.FLAT_ID=FLATBOOK.FLAT_ID)"+
" JOIN NOTIFICATION NOTIFY ON(NOTIFY.ID=NOTIFY_SENT_DET.NOTIFICATION_ID) WHERE APPR.CUST_ID=:CUST_ID AND APPR.STATUS_ID=:STATUS_ID"+ 
" AND NOTIFY.CREATED_DATE>=APPR.REGISTER_DATE";

public static final String GET_CUSTOMER_NOTIFICATIONS="SELECT DISTINCT NOTIFY.ID,NOTIFY.MESSAGE,NOTIFY_SENT_DET.FLAT_ID FROM APP_REGISTRATION APPR JOIN FLAT_BOOKING FLATBOOK ON(FLATBOOK.CUST_ID=APPR.CUST_ID)"+
" JOIN NOTIFICATION_SENT_DETAILS NOTIFY_SENT_DET ON (NOTIFY_SENT_DET.FLAT_ID=FLATBOOK.FLAT_ID)"+
" JOIN NOTIFICATION NOTIFY ON(NOTIFY.ID=NOTIFY_SENT_DET.NOTIFICATION_ID) WHERE APPR.CUST_ID=:CUST_ID AND APPR.STATUS_ID=:STATUS_ID"+ 
" AND NOTIFY.CREATED_DATE>=APPR.REGISTER_DATE";



	
public static final String GET_FLAT_BY_STATE_ID=new StringBuilder("SELECT DISTINCT FLAT.FLAT_ID,FLAT.FLAT_NO,FLATD.FLOOR_DET_ID,SITE.SITE_ID FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ")
.append(" ON(SITE.SITE_ID=BLOCKD.SITE_ID) JOIN FLOOR_DETAILS FLOORD ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID) JOIN ")
.append(" FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID) JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID) ")
.append(" JOIN FLAT_BOOKING FLATB ON(FLATB.FLAT_ID=FLATD.FLAT_ID) JOIN APP_REGISTRATION APPR ON(FLATB.CUST_ID=APPR.CUST_ID) ")
.toString();

public static final String GET_STATE_LIST="SELECT DISTINCT STATE.STATE_ID,STATE.STATE_NAME FROM STATE STATE JOIN SITE SITE ON(STATE.STATE_ID=SITE.STATE_ID)";
public static final String GET_All_STATE_LIST="SELECT DISTINCT STATE.STATE_ID,STATE.STATE_NAME FROM STATE STATE ";
public static final String GET_SITE_NOTIFYS_LIST = "SELECT DISTINCT NOTIFY.ID ,NOTIFY.MESSAGE,NOTIFY.DESCRIPTION,NOTIFY.IMAGELOCATION,NOTIFY.CREATED_DATE,CASE WHEN NDC.MODIFIED_TO IS NULL THEN NDC.ACTUAL ELSE NDC.MODIFIED_TO END AS ACTUAL,NDC.SEND_TYPE,NOTIFY.FILELOCATION,NOTIFY.NOTIFICATIONTEXT,NOTIFY.NOTIFICATION_SENT_DATE_TIME,(SELECT E.FIRST_NAME FROM EMPLOYEE E WHERE E.EMP_ID=NOTIFY.CREATED_BY ) AS NOTIF_CREATED_BY FROM NOTIFICATION NOTIFY  INNER JOIN NOTIFICATION_DETAIL_CHANGES NDC ON NOTIFY.ID=NDC.NOTIFICATION_ID ";
public static final String GET_NOTIFYS_LIST = "SELECT DISTINCT NOTIFY.ID ,NOTIFY.MESSAGE,NOTIFY.DESCRIPTION,NOTIFY.IMAGELOCATION,NOTIFY.CREATED_DATE,NOTIFYD.SEND_TO,NOTIFYD.SEND_TYPE,NOTIFY.FILELOCATION,NOTIFY.NOTIFICATIONTEXT,NOTIFY.NOTIFICATION_SENT_DATE_TIME,(SELECT E.FIRST_NAME FROM EMPLOYEE E WHERE E.EMP_ID=NOTIFY.CREATED_BY ) AS NOTIF_CREATED_BY FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAILS NOTIFYD ON(NOTIFY.ID=NOTIFYD.NOTIFICATION_ID)";
public static final String GET_NOTIFY_LIST = "SELECT DISTINCT NOTIFY.ID ,NOTIFY.MESSAGE,NOTIFY.DESCRIPTION,NOTIFY.IMAGELOCATION,NOTIFY.CREATED_DATE,CASE WHEN NOTIFYD.MODIFIED_TO IS NULL THEN NOTIFYD.ACTUAL ELSE NOTIFYD.MODIFIED_TO END AS ACTUAL,NOTIFYD.SEND_TYPE,NOTIFY.FILELOCATION,NOTIFY.NOTIFICATIONTEXT,NOTIFY.NOTIFICATION_SENT_DATE_TIME,(SELECT E.FIRST_NAME FROM EMPLOYEE E WHERE E.EMP_ID=NOTIFY.CREATED_BY ) AS NOTIF_CREATED_BY FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAIL_CHANGES NOTIFYD ON(NOTIFY.ID=NOTIFYD.NOTIFICATION_ID)";
public static final String GET_NOTIFYS = "SELECT DISTINCT NOTIFY.ID FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAILS NOTIFYD ON(NOTIFY.ID=NOTIFYD.NOTIFICATION_ID)";
//public static final String ROW_COUNT = "SELECT COUNT(*) FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAILS NOTIFYD ON(NOTIFY.ID=NOTIFYD.NOTIFICATION_ID)  ";
public static final String GET_SITE_NOTIFYS = "SELECT DISTINCT NOTIFY.ID FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAIL_CHANGES NDC ON(NOTIFY.ID=NDC.NOTIFICATION_ID)";
public static final String Notify_ROW_COUNT="SELECT COUNT( NDC.NOTIFICATION_ID) FROM NOTIFICATION_DETAIL_CHANGES NDC";
public static final String ROW_COUNT = "SELECT COUNT(DISTINCT NOTIFY.ID) FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAILS NOTIFYD ON(NOTIFY.ID=NOTIFYD.NOTIFICATION_ID)  ";
public static final String SITE_ROW_COUNT="SELECT COUNT(DISTINCT NOTIFY.ID) FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAIL_CHANGES NDC ON(NOTIFY.ID=NDC.NOTIFICATION_ID)";
public static final String GET_SITE_ROW_COUNT="SELECT COUNT(DISTINCT NOTIFY.ID) FROM NOTIFICATION NOTIFY JOIN NOTIFICATION_DETAIL_CHANGES NOTIFYD ON(NOTIFY.ID=NOTIFYD.NOTIFICATION_ID)";
public static final String GET_FLAT_DETAILS="SELECT SITE.SITE_ID,SITE.NAME,BLOCK.BLOCK_ID,BLOCK.NAME AS BLOCKNAME,BLOCKD.BLOCK_DET_ID,"+
" FLOOR.FLOOR_ID,FLOOR.NAME AS FNAME,FLOORD.FLOOR_DET_ID,FLAT.FLAT_NO,FLAT.FLAT_ID,FLATD.FLAT_DET_ID"+
" FROM SITE SITE JOIN BLOCK_DETAILS "+
" BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID) JOIN BLOCK BLOCK ON(BLOCK.BLOCK_ID=BLOCKD.BLOCK_ID) JOIN FLOOR_DETAILS FLOORD"+ 
" ON(BLOCKD.BLOCK_DET_ID=FLOORD.BLOCK_DET_ID) JOIN FLOOR FLOOR ON(FLOOR.FLOOR_ID=FLOORD.FLOOR_ID)"+
" JOIN  FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID) JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID)";

public static final String GET_FLOOR_DETAILS="SELECT SITE.SITE_ID,SITE.NAME,BLOCK.BLOCK_ID,BLOCK.NAME AS BLOCKNAME,BLOCKD.BLOCK_DET_ID,FLOOR.FLOOR_ID,FLOOR.NAME AS FLOORNAME,FLOORD.FLOOR_DET_ID "+
"FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID) JOIN BLOCK BLOCK ON(BLOCK.BLOCK_ID=BLOCKD.BLOCK_ID) JOIN FLOOR_DETAILS FLOORD "+
"ON(BLOCKD.BLOCK_DET_ID=FLOORD.BLOCK_DET_ID) JOIN FLOOR FLOOR ON(FLOOR.FLOOR_ID=FLOORD.FLOOR_ID)";

public static final String GET_BLOCK_DETAILS="SELECT SITE.SITE_ID,SITE.NAME,BLOCK.BLOCK_ID,BLOCK.NAME AS BLOCKNAME,BLOCKD.BLOCK_DET_ID "+
" FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID) JOIN BLOCK BLOCK ON(BLOCK.BLOCK_ID=BLOCKD.BLOCK_ID)";

public static final String GET_SITE_DETAILS="SELECT SITE.SITE_ID,SITE.NAME,SALES_FORCE_SITE_NAME FROM SITE SITE ";

public static final String GET_NOTIFICATION_LEVEL_MENU_DETAILS_BY_MENU_NAME_BY_EMP_ID = " SELECT MENULM.LEVEL_ID,MENULM.APPROVE_TO,EMPLM.MENU_LEVEL_MAP_ID FROM MENU MENU JOIN MENU_LEVEL_MAPPING MENULM ON(MENU.MENU_ID=MENULM.MENU_ID) " +
" JOIN EMPLOYEE_LEVEL_MAPPING EMPLM ON(MENULM.MENU_LEVEL_MAP_ID=EMPLM.MENU_LEVEL_MAP_ID)";

public static final String GET_NOTIFICATION_APPROVAL_STATUS = "SELECT NOTIFICATION_APPROVAL_ID,APPROVAL_LEVEL,STATUS FROM NOTIFICATION_APPROVAL NOTIFYAPP JOIN MENU_LEVEL_MAPPING MENULM " + 
		" ON(NOTIFYAPP.APPROVAL_LEVEL=MENULM.LEVEL_ID) JOIN MENU MENU ON(MENULM.MENU_ID=MENU.MENU_ID)";

public static final String GET_NOTIFYS_PROJECT_LEVEL_NOTIFICATION_SPECIFIC = 
                                                         new StringBuilder(" JOIN NOTIFICATION_SENT_DETAILS NSD ")
                                                         .append(" ON(NSD.NOTIFICATION_ID = NOTIFYD.NOTIFICATION_ID) ")
                                                         .append(" JOIN FLAT_DETAILS FD ")
                                                         .append(" ON(NSD.FLAT_ID = FD.FLAT_ID) ")
                                                         .append(" INNER JOIN FLOOR_DETAILS FLD  ")
                                                         .append(" ON FLD.FLOOR_DET_ID = FD.FLOOR_DET_ID  ")
                                                         .append(" INNER JOIN BLOCK_DETAILS BD ")
                                                         .append(" ON FLD.BLOCK_DET_ID = BD.BLOCK_DET_ID ")
                                                         .append(" INNER JOIN SITE S  ")
                                                         .append(" ON NDC.SITE_ID = S.SITE_ID ")
                                                         .append(" INNER JOIN NOTIFICATION_APPROVAL NA ON (NA.NOTIFICATION_ID=NOTIFY.ID) ")
                                                         .toString();

public static final String GET_NOTIFYS_PROJECT_LEVEL_NOTIFICATION_SPECIFIC_CHANGES = new StringBuilder(" JOIN NOTIFICATION_SENT_DETAILS NSD ")
           .append(" ON(NSD.NOTIFICATION_ID = NDC.NOTIFICATION_ID) ")
           .append(" INNER JOIN SITE S  ")
           .append(" ON NDC.ACTUAL = S.SITE_ID ")
           .append(" INNER JOIN NOTIFICATION_APPROVAL NA ON (NA.NOTIFICATION_ID=NOTIFY.ID) ")
           .toString();


	public static final String QRY_TO_INSERT_NOTIFICATION_DET_CHANGES = new StringBuilder(" INSERT INTO ")
		.append(" NOTIFICATION_DETAIL_CHANGES ")
		.append(" (NOTIFICATION_DET_CHANGES_ID, ")
		.append(" SEND_TYPE, ")
		.append(" NOTIFICATION_ID, ")
		.append(" ACTUAL, ")
		.append(" STATUS, ")
		.append(" CREATED_BY, ")
		.append(" CREATED_DATE) ")
		.append(" VALUES( ")
		.append(" NOTIFICATION_DETAIL_CHANGES_SEQ.NEXTVAL, ")
		.append(" :SEND_TYPE, ")
		.append(" :NOTIFICATION_ID, ")
		.append(" :ACTUAL, ")
		.append(" :STATUS, ")
		.append(" :CREATED_BY, ")
		.append(" SYSDATE) ")
		.toString();
	
	public static final String QRY_TO_INSERT_NOTIFICATION_CHANGES = new StringBuilder(" INSERT INTO ")
		.append(" NOTIFICATION_CHANGES ")
		.append(" (NOTIFICATION_CHANGES_ID, ")
		.append(" NOTIFICATION_ID, ")
		.append(" SEND_TYPE,  ")
		.append(" ACTUAL, ")
		.append(" STATUS, ")
		.append(" CREATED_BY, ")
		.append(" CREATED_DATE) ")
		.append(" VALUES( ")
		.append(" NOTIFICATION_CHANGES_SEQ.NEXTVAL, ")
		.append(" :NOTIFICATION_ID, ")
		.append(" :SEND_TYPE, ")
		.append(" :ACTUAL, ")
		.append(" :STATUS, ")
		.append(" :CREATED_BY, ")
		.append(" SYSDATE) ")
		.toString();
	
	public static final String QRY_TO_INACTIVE_OLD_NOTIFICATION_CHANGES = new StringBuilder(" UPDATE ")
		.append(" NOTIFICATION_CHANGES ")
		.append(" SET STATUS = :STATUS, ")
		.append(" MODIFIED_BY = :MODIFIED_BY, ")
		.append(" MODIFIED_DATE = SYSDATE ")
		.append(" WHERE NOTIFICATION_ID = :NOTIFICATION_ID ")
		.append(" AND STATUS = :STATUS_ID ")
		.toString();
	
	public static final String QRY_TO_INACTIVE_OLD_NOTIFICATION_DETAIL_CHANGES = new StringBuilder(" UPDATE ")
		.append(" NOTIFICATION_DETAIL_CHANGES ")
		.append(" SET STATUS = :STATUS, ")
		.append(" MODIFIED_BY = :MODIFIED_BY, ")
		.append(" MODIFIED_DATE = SYSDATE ")
		.append(" WHERE NOTIFICATION_ID = :NOTIFICATION_ID ")
		.append(" AND STATUS = :STATUS_ID ")
		.toString();
	
	public static final String QRY_TO_INACTIVE_OLD_NOTIFICATION = new StringBuilder(" UPDATE ")
		.append(" NOTIFICATION ")
		.append(" SET STATUS_ID = :STATUS, ")
		.append(" MODIFIED_BY = :MODIFIED_BY, ")
		.append(" MODIFIED_DATE = SYSDATE ")
		.append(" WHERE ID = :NOTIFICATION_ID ")
		.append(" AND STATUS_ID = :STATUS_ID ")
		.toString();
		
		
	public static final String QRY_TO_GET_NOTIFICATION_DETAIL_CHANGES = new StringBuilder(" SELECT ")
		.append(" NDC.NOTIFICATION_DET_CHANGES_ID, ")
		.append(" NDC.SEND_TYPE, ")
		.append(" NDC.NOTIFICATION_ID, ")
		.append(" COALESCE(NDC.MODIFIED_TO, NDC.ACTUAL) AS ACTUAL, ")
		.append(" NDC.MODIFIED_TO, ")
		.append(" NDC.STATUS, ")
		.append(" NDC.MODIFIED_BY, ")
		.append(" NDC.CREATED_BY, ")
		.append(" NDC.CREATED_DATE, ")
		.append(" NDC.MODIFIED_DATE ")
		.append(" FROM NOTIFICATION_DETAIL_CHANGES NDC ")
		.append(" WHERE NDC.NOTIFICATION_ID = :NOTIFICATION_ID ")
		.append(" AND NDC.STATUS = :STATUS ")
		.toString();
		
	public static final String QRY_TO_UPDATE_NOTIFICATION__DETAIL_CHANGES = new StringBuilder(" UPDATE ")
		.append(" NOTIFICATION_DETAIL_CHANGES ")
		.append(" SET ACTUAL = :ACTUAL, ")
		.append(" MODIFIED_TO = :MODIFIED_TO, ")
		.append(" MODIFIED_BY = :MODIFIED_BY, ")
		.append(" MODIFIED_DATE = SYSDATE, ")
		.append(" STATUS = :STATUS ")
		.append(" WHERE NOTIFICATION_DET_CHANGES_ID = :NOTIFICATION_DET_CHANGES_ID ")
		.toString();
		
	public static final String QRY_TO_INSERT_MODIFIED_NOTIFICATION__DETAIL_CHANGES = new StringBuilder(" INSERT INTO ")
		.append(" NOTIFICATION_DETAIL_CHANGES ")
		.append(" (NOTIFICATION_DET_CHANGES_ID, ")
		.append(" SEND_TYPE, ")
		.append(" NOTIFICATION_ID, ")
		.append(" MODIFIED_TO, ")
		.append(" STATUS, ")
		.append(" MODIFIED_BY, ")
		.append(" MODIFIED_DATE) ")
		.append(" VALUES( ")
		.append(" NOTIFICATION_DETAIL_CHANGES_SEQ.NEXTVAL, ")
		.append(" :SEND_TYPE, ")
		.append(" :NOTIFICATION_ID, ")
		.append(" :MODIFIED_TO, ")
		.append(" :STATUS, ")
		.append(" :MODIFIED_BY, ")
		.append(" SYSDATE) ")
		.toString();
		
	public static final String QRY_TO_GET_NOTIFICATION_CHANGES = new StringBuilder(" SELECT ")
		.append(" NC.NOTIFICATION_CHANGES_ID, ")
		.append(" NC.NOTIFICATION_ID, ")
		.append(" NC.SEND_TYPE, ")
		.append(" COALESCE(NC.MODIFIED_TO, NC.ACTUAL) AS ACTUAL, ")
		.append(" NC.MODIFIED_TO, ")
		.append(" NC.STATUS, ")
		.append(" NC.MODIFIED_BY, ")
		.append(" NC.CREATED_BY, ")
		.append(" NC.CREATED_DATE, ")
		.append(" NC.MODIFIED_DATE ")
		.append(" FROM NOTIFICATION_CHANGES NC ")
		.append(" WHERE NOTIFICATION_ID = :NOTIFICATION_ID ")
		.append(" AND STATUS = :STATUS ")
		.toString();
		
	public static final String QRY_TO_UPDATE_NOTIFICATION_CHANGES = new StringBuilder(" UPDATE ")
		.append(" NOTIFICATION_CHANGES ")
		.append(" SET ACTUAL = :ACTUAL, ")
		.append(" MODIFIED_TO = :MODIFIED_TO, ")
		.append(" MODIFIED_BY = :MODIFIED_BY, ")
		.append(" STATUS = :STATUS, ")
		.append(" MODIFIED_DATE = SYSDATE ")
		.append(" WHERE NOTIFICATION_CHANGES_ID = :NOTIFICATION_CHANGES_ID ")
		.toString();
		
	public static final String QRY_TO_INSERT_MODIFIED_NOTIFICATION_CHANGES = new StringBuilder(" INSERT INTO ")
		.append(" NOTIFICATION_CHANGES ")
		.append(" (NOTIFICATION_CHANGES_ID, ")
		.append(" NOTIFICATION_ID, ")
		.append(" SEND_TYPE, ")
		.append(" MODIFIED_TO, ")
		.append(" STATUS, ")
		.append(" MODIFIED_BY, ")
		.append(" MODIFIED_DATE) ")
		.append(" VALUES( ")
		.append(" NOTIFICATION_CHANGES_SEQ.NEXTVAL, ")
		.append(" :NOTIFICATION_ID, ")
		.append(" :SEND_TYPE, ")
		.append(" :MODIFIED_TO, ")
		.append(" :STATUS, ")
		.append(" :MODIFIED_BY, ")
		.append(" SYSDATE) ")
		.toString();
		
	public static final String QRY_TO_GET_NOTIFICATION_APPROVAL_LEVELS = new StringBuilder(" SELECT ")
		.append(" NAL.NOT_APR_LEV_ID, ")
		.append(" NAL.NOT_SET_OF_LEV_ID, ")
		.append(" NAL.NXT_NOT_SET_OF_LEV_ID, ")
		.append(" NAL.CREATED_DATE, ")
		.append(" NAL.CREATED_BY, ")
		.append(" NAL.STATUS_ID ")
		.append(" FROM NOTIFICATION_APPROVAL_LEVELS NAL ")
		.toString();
		
	public static final String QRY_TO_INSERT_INTO_NOTIFICATION_APPROVAL = new StringBuilder(" INSERT INTO ")
		.append(" NOTIFICATION_APPROVAL( ")
		.append(" NOT_APR_ID, ")
		.append(" NOTIFICATION_ID, ")
		.append(" NOT_APR_LEV_ID, ")
		.append(" COMMENTS, ")
		.append(" CREATED_DATE, ")
		.append(" CREATED_BY, ")
		.append(" STATUS_ID) ")
		.append(" VALUES( ")
		.append(" NOTIFICATION_APPROVAL_SEQ.NEXTVAL, ")
		.append(" :notificationId, ")
		.append(" :notAprLevId, ")
		.append(" :comments, ")
		.append(" SYSDATE, ")
		.append(" :createdBy, ")
		.append(" :statusId) ")
		.toString();
		
	public static final String QRY_TO_INSERT_INTO_NOTIFICATION_APPROVAL_STATISTICS = new StringBuilder(" INSERT INTO ")
		.append(" NOTIFICATION_APPROVAL_STATISTICS( ")
		.append(" NOT_APR_STCS_ID, ")
		.append(" NOTIFICATION_ID, ")
		.append(" NOT_APR_LEV_ID, ")
		.append(" COMMENTS, ")
		.append(" CREATED_DATE, ")
		.append(" CREATED_BY, ")
		.append(" STATUS_ID) ")
		.append(" VALUES( ")
		.append(" NOTIFICATION_APPROVAL_STATISTICS_SEQ.NEXTVAL, ")
		.append(" :notificationId, ")
		.append(" :notAprLevId, ")
		.append(" :comments, ")
		.append(" SYSDATE, ")
		.append(" :createdBy, ")
		.append(" :statusId) ")
		.toString();
		
	public static final String QRY_TO_UPDATE_NOTIFICATION_APPROVAL = new StringBuilder(" UPDATE ")
		.append(" NOTIFICATION_APPROVAL ")
		.append(" SET NOT_APR_LEV_ID = :notAprLevId, ")
		.append(" COMMENTS = :comments, ")
		.append(" CREATED_DATE = SYSDATE, ")
		.append(" CREATED_BY = :createdBy, ")
		.append(" STATUS_ID = :statusId ")
		.append(" WHERE NOTIFICATION_ID = :notificationId ")
		.toString();
		
	public static final String QRY_TO_GET_NOTIFICATION_APPROVAL = new StringBuilder(" SELECT ")
		.append(" NA.NOTIFICATION_ID, ")
		.append(" NA.NOT_APR_ID, ")
		.append(" NA.NOT_APR_LEV_ID, ")
		.append(" NA.COMMENTS, ")
		.append(" NA.CREATED_DATE, ")
		.append(" E.FIRST_NAME AS CREATED_BY_NAME, ")
		.append(" NA.CREATED_BY, ")
		.append(" NA.STATUS_ID, ")
		.append(" NT.MESSAGE ")
			.append(" ,(SELECT S.NAME FROM SITE S INNER JOIN NOTIFICATION_DETAIL_CHANGES NDC ON S.SITE_ID=NDC.ACTUAL WHERE NDC.SEND_TYPE=1 AND NDC.NOTIFICATION_ID=NA.NOTIFICATION_ID) AS SITE_NAME ")
		.append(" FROM NOTIFICATION_APPROVAL NA ")
		.append(" JOIN NOTIFICATION NT ON ")
		.append(" (NT.ID = NA.NOTIFICATION_ID) ")
		.append(" INNER JOIN  EMPLOYEE E ON ")
		.append(" (NA.CREATED_BY=E.EMP_ID) ")
		.append(" JOIN NOTIFICATION_APPROVAL_LEVELS NAL ON ")
		.append(" (NAL.NOT_APR_LEV_ID = NA.NOT_APR_LEV_ID) ")
		.append(" JOIN NOTIFICATION_SET_OF_LEVELS NSL ON ")
		.append(" (NSL.NOT_SET_OF_LEV_ID = NAL.NOT_SET_OF_LEV_ID) ")
		.append(" JOIN NOTIFICATION_SET_OF_LVL_EMP_MAP NSLEM ON ")
		.append(" (NSLEM.NOT_SET_OF_LEV_ID = NSL.NOT_SET_OF_LEV_ID) ")
		.append(" WHERE NSL.TYPE =:TYPE AND NA.STATUS_ID IN (:STATUS_IDS) ")
		.append(" AND NSL.STATUS_ID =:STATUS_ID AND NAL.STATUS_ID =:STATUS_ID ")
		.append(" AND NT.STATUS_ID =:STATUS_ID ")
		.toString();
		
	public static final String QRY_TO_GET_NOTIFICATION_APPROVAL_ROW_COUNT = new StringBuilder(" SELECT ")
		.append(" COUNT(*) FROM NOTIFICATION_APPROVAL NA ")
		.append(" JOIN NOTIFICATION NT ON ")
		.append(" (NT.ID = NA.NOTIFICATION_ID) ")
		.append(" JOIN NOTIFICATION_APPROVAL_LEVELS NAL ON ")
		.append(" (NAL.NOT_APR_LEV_ID = NA.NOT_APR_LEV_ID) ")
		.append(" JOIN NOTIFICATION_SET_OF_LEVELS NSL ON ")
		.append(" (NSL.NOT_SET_OF_LEV_ID = NAL.NOT_SET_OF_LEV_ID) ")
		.append(" JOIN NOTIFICATION_SET_OF_LVL_EMP_MAP NSLEM ON ")
		.append(" (NSLEM.NOT_SET_OF_LEV_ID = NSL.NOT_SET_OF_LEV_ID) ")
		.append(" WHERE NSL.TYPE =:TYPE AND NA.STATUS_ID IN (:STATUS_IDS) ")
		.append(" AND NSL.STATUS_ID =:STATUS_ID AND NAL.STATUS_ID =:STATUS_ID ")
		.append(" AND NT.STATUS_ID =:STATUS_ID ")
		.toString();
		
	public static final String QRY_TO_GET_SITE_BLOCK_FLOOR_FLAT_DATA = new StringBuilder()
		.append(" FROM FLAT_DETAILS FD ")
		.append(" INNER JOIN FLAT F ")
		.append(" ON FD.FLAT_ID=F.FLAT_ID ")
		.append(" INNER JOIN FLOOR_DETAILS FLD ")
		.append(" ON FD.FLOOR_DET_ID=FLD.FLOOR_DET_ID ")
		.append(" INNER JOIN FLOOR FL ")
		.append(" ON FLD.FLOOR_ID=FL.FLOOR_ID ")
		.append(" INNER JOIN BLOCK_DETAILS BD ")
		.append(" ON FLD.BLOCK_DET_ID=BD.BLOCK_DET_ID ")
		.append(" INNER JOIN BLOCK B ")
		.append(" ON BD.BLOCK_ID=B.BLOCK_ID ")
		.append(" INNER JOIN SITE S ")
		.append(" ON BD.SITE_ID=S.SITE_ID ")
		.append(" INNER JOIN ADDRESS AD ")
		.append(" ON AD.ADDRESS_ID = S.ADDRESS_ID ")
		.toString ();
		
	public static final String QRY_TO_GET_FLAT_TYPE_METADATA = new StringBuilder(" SELECT ")
		.append(" FM.FLAT_TYPE_META_ID AS SITE_ID, ")
		.append(" FM.STATUS AS NAME ")
		.append(" FROM FLAT_TYPE_METADATA FM ")
		.toString();
		
	public static final String QRY_TO_CHECK_NOTIFICATION_EXISTACNE = new StringBuilder(" SELECT ")
		.append(" COUNT(*) FROM NOTIFICATION ")
		.append(" WHERE ID =:NOTIFICATION_ID ")
		.toString();
		
	public static final String QRY_TO_GET_NOTIFICATION_APPROVALS = new StringBuilder(" SELECT ")
		.append(" NA.NOT_APR_ID, ")
		.append(" NA.NOTIFICATION_ID, ")
		.append(" NA.NOT_APR_LEV_ID, ")
		.append(" NA.COMMENTS, ")
		.append(" NA.CREATED_DATE, ")
		.append(" NA.CREATED_BY, ")
		.append(" NA.STATUS_ID ")
		.append(" FROM NOTIFICATION_APPROVAL NA ")
		.append(" WHERE NA.NOTIFICATION_ID=:NOTIFICATION_ID ")
		.toString();
	
	public static final String FLAT_DETAILS =" FLAT.FLAT_ID AS ID,FLAT.FLAT_ID,FLAT.FLAT_NO,CONCAT(CONCAT(CONCAT(CONCAT(SITE.SHORT_FORM,'-'),BLOCK.NAME),'-'),FLAT.FLAT_NO) AS NAME,FLATD.FLAT_DET_ID AS DETID,FLOORD.FLOOR_DET_ID AS MAPID ";
	
	public static final String GET_ACTIVE_FLAT_WITH_APP_REGISTRATION =new StringBuilder(SELECT).append(DISTINCT).append(FLAT_DETAILS)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT).toString();
	
	public static final String QRY_TO_GET_EMPLOYEE_DETAILS_BY_NOT_APR_LEV_ID = new StringBuilder(" SELECT ")
			.append(" EMP.CS_EMP_ID,EMP.EMP_ID, ")
			.append(" EMP.FIRST_NAME,EMP.LAST_NAME,")
			.append(" EMP.EMAIL,EMP.STATUS_ID, ")
			.append(" EMP.CREATED_DATE,EMP.MODIFIED_DATE, ")
			.append(" EMP.MOBILE_NO,EMP.USER_PROFILE, ")
			.append(" EMP.SALESFORCE_EMP_NAME,EMP.SUMADHURA_EMP_ID FROM EMPLOYEE EMP  ")
			.append(" JOIN NOTIFICATION_SET_OF_LVL_EMP_MAP NSLEM ON(NSLEM.EMP_ID=EMP.EMP_ID) ")
			.append(" JOIN NOTIFICATION_APPROVAL_LEVELS NAL ON(NAL.NOT_SET_OF_LEV_ID=NSLEM.NOT_SET_OF_LEV_ID) ")
			.append(" WHERE EMP.STATUS_ID=:STATUS_ID ")
			.append(" AND NAL.NOT_APR_LEV_ID=:NOT_APR_LEV_ID ")
			.toString();
	
	public static final String ACTIVE_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG=new StringBuilder()
			.append(" FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID AND SITE.STATUS_ID=2 AND BLOCKD.STATUS_ID=6) ")
			.append(" JOIN BLOCK BLOCK ON(BLOCKD.BLOCK_ID=BLOCK.BLOCK_ID) JOIN FLOOR_DETAILS FLOORD JOIN FLOOR FLOOR ON(FLOORD.FLOOR_ID=FLOOR.FLOOR_ID) ")
			.append(" ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID AND FLOORD.STATUS_ID=6 ) JOIN FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID AND FLATD.STATUS_ID=6) ")
			.append(" JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID) JOIN FLAT_BOOKING FLATB ON(FLATB.FLAT_ID=FLATD.FLAT_ID AND FLATB.STATUS_ID=6) ")
			.toString();
	
	public static final String GET_ACTIVE_FLAT_WITHOUT_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(FLAT_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG).toString();
	
	public static final String GET_ACTIVE_FLOOR_WITHOUT_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(FLOOR_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG).toString();
	
	public static final String GET_ACTIVE_BLOCK_WITHOUT_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(BLOCK_DD_COL)
			.append(ACTIVE_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG).toString();
	
	
	
	public static final String FLAT_DD_COL_FOR_ALL=" FLAT.FLAT_ID AS ID ,CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(SITE.SHORT_FORM,'-'),BLOCK.NAME),'-'),FLAT.FLAT_NO),'-'),S.STATUS) AS NAME,FLATD.FLAT_DET_ID AS DETID,FLOORD.FLOOR_DET_ID AS MAPID,FLATB.FLAT_BOOK_ID,FLATB.CUST_ID,FLATB.STATUS_ID,S.STATUS,FLATB.SALESFORCE_BOOKING_ID , SITE.SALES_FORCE_SITE_NAME AS SALES_FORCE_SITE_NAME ";
	
	public static final String ALL_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG=new StringBuilder()
			.append(" FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID AND SITE.STATUS_ID=2 AND BLOCKD.STATUS_ID=6) ")
			.append(" JOIN BLOCK BLOCK ON(BLOCKD.BLOCK_ID=BLOCK.BLOCK_ID) JOIN FLOOR_DETAILS FLOORD JOIN FLOOR FLOOR ON(FLOORD.FLOOR_ID=FLOOR.FLOOR_ID) ")
			.append(" ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID AND FLOORD.STATUS_ID=6 ) JOIN FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID AND FLATD.STATUS_ID=6) ")
			.append(" JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID) JOIN FLAT_BOOKING FLATB ON(FLATB.FLAT_ID=FLATD.FLAT_ID )  ")
			.append(" JOIN STATUS S ON(FLATB.STATUS_ID=S.STATUS_ID) ")
			.toString();
	
	public static final String ALL_SITE_BLCOK_FLOOR_FLAT_S=new StringBuilder()
			.append(" FROM SITE SITE JOIN BLOCK_DETAILS BLOCKD ON(SITE.SITE_ID=BLOCKD.SITE_ID AND SITE.STATUS_ID=2 AND BLOCKD.STATUS_ID=6) ")
			.append(" JOIN BLOCK BLOCK ON(BLOCKD.BLOCK_ID=BLOCK.BLOCK_ID AND BLOCK.STATUS_ID=6) JOIN FLOOR_DETAILS FLOORD JOIN FLOOR FLOOR ON(FLOORD.FLOOR_ID=FLOOR.FLOOR_ID) ")
			.append(" ON(FLOORD.BLOCK_DET_ID=BLOCKD.BLOCK_DET_ID AND FLOORD.STATUS_ID=6 ) JOIN FLAT_DETAILS FLATD ON(FLATD.FLOOR_DET_ID=FLOORD.FLOOR_DET_ID AND FLATD.STATUS_ID=6) ")
			.append(" JOIN FLAT FLAT ON(FLAT.FLAT_ID=FLATD.FLAT_ID)  ")
			.toString();
	
	public static final String GET_ALL_FLAT_WITHOUT_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(FLAT_DD_COL_FOR_ALL)
			.append(ALL_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG).toString();
	
	public static final String GET_ALL_FLOOR_WITHOUT_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(FLOOR_DD_COL)
			.append(ALL_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG).toString();
	
	public static final String GET_ALL_BLOCK_WITHOUT_APP_REG=new StringBuilder(SELECT).append(DISTINCT).append(BLOCK_DD_COL)
			.append(ALL_SITE_BLCOK_FLOOR_FLAT_WITHOUT_APP_REG).toString();
	
	public static final String GET_ALL_BLOCK_S=new StringBuilder(SELECT).append(DISTINCT).append(BLOCK_DD_COL)
			.append(ALL_SITE_BLCOK_FLOOR_FLAT_S).toString();
	
	public static final String QRY_TO_UPDATE_NOTIFICATION_NUMBER_OF_FLATS_TO_SENT = new StringBuilder(" UPDATE ")
			.append(" NOTIFICATION  ")
			.append(" SET NUMBER_OF_FLATS_TO_SENT = :NUMBER_OF_FLATS_TO_SENT ")
			.append(" WHERE ID = :NOTIFICATION_ID ")
			.toString();
	
	
	public static final String QRY_TO_GET_VIEW_REPORT = new StringBuilder(" SELECT ")
			.append(" DISTINCT NOTI.ID AS NOTIFICATION_ID, ")
			.append(" NOTI.MESSAGE,NOTI.DESCRIPTION,NOTI.NOTIFICATIONTEXT,NOTD.SEND_TO, ")
			.append(" NOTI.OS_TYPE,NOTD.SEND_TYPE, ")
			.append(" CASE WHEN NOTD.SEND_TYPE=1 THEN 'Project'  ")
			.append(" WHEN NOTD.SEND_TYPE=2 THEN 'Block' ")
			.append(" WHEN NOTD.SEND_TYPE=3 THEN 'Floor' ")
			.append(" WHEN NOTD.SEND_TYPE=4 THEN 'FLAT' END AS NOTIFICATION_TYPE, ")
			.append(" CASE WHEN NOTI.NUMBER_OF_FLATS_TO_SENT IS NULL THEN 0 ELSE NOTI.NUMBER_OF_FLATS_TO_SENT END AS NUMBER_OF_FLATS_TO_SENT  ")
			.append(" FROM NOTIFICATION NOTI ")
			.append(" INNER JOIN NOTIFICATION_DETAILS NOTD ON NOTI.ID=NOTD.NOTIFICATION_ID ")
			.append(" WHERE NOTI.ID=:NOTIFICATION_ID ")
			.toString();

	public static final String QRY_TO_GET_STATE_NAME = new StringBuilder(" SELECT ")
			.append(" DISTINCT St.STATE_NAME FROM STATE St   ")
			.append("  INNER JOIN SITE S  ")
			.append("ON St.STATE_ID=S.STATE_ID ")
			.append(" INNER JOIN NOTIFICATION_DETAILS NSD  ON ")
			.append("  NSD.NOTIFICATION_ID=:NOTIFICATION_ID ")
			.append(" AND NSD.SEND_TO=:SEND_TO ")
			.append(" where st.STATE_ID =:SEND_TO ")
			.toString();
	
	public static final String QRY_TO_GET_SITE_NAME = new StringBuilder(" SELECT ")
			.append(" DISTINCT S.NAME AS SITE_NAME   ")
			.append(" FROM  FLAT_BOOKING FB INNER JOIN FLAT F  ")
			.append(" ON FB.FLAT_ID = F.FLAT_ID  ")
			.append(" INNER JOIN FLOOR_DETAILS FD  ")
			.append(" ON F.FLOOR_DET_ID = FD.FLOOR_DET_ID ")
			.append(" INNER JOIN FLOOR FL  ")
			.append(" ON FL.FLOOR_ID = FD.FLOOR_ID   ")
			.append(" INNER JOIN BLOCK_DETAILS BD  ")
			.append(" ON FD.BLOCK_DET_ID = BD.BLOCK_DET_ID  ")
			.append(" INNER JOIN BLOCK BL  ")
			.append(" ON BL.BLOCK_ID = BD.BLOCK_ID    ")
			.append(" INNER JOIN SITE S ")
			.append(" ON BD.SITE_ID = S.SITE_ID  ")
			.append(" INNER JOIN NOTIFICATION_SENT_DETAILS NSD  ")
			.append(" ON F.FLAT_ID=NSD.FLAT_ID AND  ")
			.append(" NSD.NOTIFICATION_ID=:NOTIFICATION_ID  ")
			.toString();
	public static final String QRY_TO_GET_NON_CUST_RECIEVED_COUNT = new StringBuilder(" SELECT ")
			.append("  COUNT(DISTINCT DEVICE_ID) RECIEVED_COUNT  ")
			.append(" FROM  NONCUST_NOTIFICATION_SENT_DET NOTSD")
			.append(" WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID AND NOTSD.STATUS_ID=:STATUS_ID  ")
			.toString();
	
	public static final String QRY_TO_GET_RECIEVED_COUNT = new StringBuilder(" SELECT ")
			.append("  COUNT(DISTINCT FLAT_ID) RECIEVED_COUNT  ")
			.append(" FROM NOTIFICATION_SENT_DETAILS NOTSD  ")
			.append(" WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID AND NOTSD.STATUS_ID=:STATUS_ID  ")
			.toString();
	
	public static final String QRY_TO_GET_DEVICES_SENT_COUNT = new StringBuilder(" SELECT ")
			.append(" COUNT(DISTINCT DEVICE_ID) AS  NON_OF_DEVICES_TO_SENT ")
			.append(" FROM NONCUST_NOTIFICATION_SENT_DET NOTSD  ")
			.append(" WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID ")
			.toString();
	
	public static final String QRY_TO_GET_SENTFLAT_COUNT = new StringBuilder(" SELECT ")
			.append(" COUNT(DISTINCT FLAT_ID) AS  NUMBER_OF_FLATS_TO_SENT ")
			.append(" FROM NOTIFICATION_SENT_DETAILS NOTSD  ")
			.append(" WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID ")
			.toString();
	
	public static final String QRY_TO_GET_NON_CUST_VIEW_COUNT = new StringBuilder(" SELECT ")
			.append(" COUNT(DISTINCT DEVICE_ID) AS VIEW_COUNT  ")
			.append(" FROM  NONCUST_NOTIFICATION_SENT_DET NOTSD  ")
			.append(" WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID AND NOTSD.IS_VIEWED=:ISVIEWED  ")
			.toString();
	public static final String QRY_TO_GET_VIEW_COUNT = new StringBuilder(" SELECT ")
			.append(" COUNT(DISTINCT FLAT_ID) AS VIEW_COUNT  ")
			.append(" FROM NOTIFICATION_SENT_DETAILS NOTSD  ")
			.append(" WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID AND NOTSD.ISVIEWED=:ISVIEWED  ")
			.toString();
	
	public static final String QRY_TO_GET_NON_CUST_VIEW_DETAILS_LIST = new StringBuilder(" SELECT ")
			.append(" D.DEVICE_ID,NOTSD.DEVICE_ID,CASE WHEN D.OS_TYPE IS NULL THEN '-' ELSE D.OS_TYPE END AS OS_TYPE,C.NAME AS CUST_NAME,NOTSD.IS_VIEWED,")
			.append("   CASE WHEN NOTSD.IS_VIEWED=1 THEN 'VIEWED' ELSE 'NOT VIEWED' END AS VIEW_STATUS, ")
			.append(" CASE WHEN NOTSD.IS_VIEWED=1 THEN NOTSD.MODIFIED_DATE ELSE NULL END AS VIEWED_TIME , ")
			.append("   NOTSD.STATUS_ID ,  ")
			.append("  CASE WHEN NOTSD.STATUS_ID=21 THEN 'RECIEVED' WHEN NOTSD.STATUS_ID=22 THEN 'NOT RECIEVED' WHEN NOTSD.STATUS_ID=116 THEN 'APP NOT REGISTERED' END AS DELIVERED_STATUS, ")
			.append(" CASE WHEN NOTSD.STATUS_ID=21 THEN NOTSD.CREATED_DATE WHEN NOTSD.STATUS_ID=22 THEN NULL END AS DELIVERED_TIME,  ")
			
			.append("  	D.DEVICE_MODEL   ")
			.append("  FROM NOTIFICATION NOTI ")
			.append("  INNER JOIN NONCUST_NOTIFICATION_SENT_DET NOTSD ON NOTSD.NOTIFICATION_ID=NOTI.ID   ")
			.append("  INNER  JOIN DEVICE D ON D.DEVICE_ID=NOTSD.DEVICE_ID  ")
			.append("   INNER JOIN NON_CUSTOMER C ON D.DEVICE_ID=C.ID   ")
			.append("   WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID  ")
			.toString();
	
	public static final String QRY_TO_GET_VIEW_DETAILS_LIST = new StringBuilder(" SELECT ")
			.append(" F.FLAT_NO,NOTSD.FLAT_ID,F.FLAT_NO,CASE WHEN D.OS_TYPE IS NULL THEN '-' ELSE D.OS_TYPE END AS OS_TYPE,C.FIRST_NAME ||' '|| C.LAST_NAME AS CUST_NAME,NOTSD.ISVIEWED,   ")
			.append(" CASE WHEN NOTSD.ISVIEWED=1 THEN 'VIEWED' ELSE 'NOT VIEWED' END AS VIEW_STATUS,   ")
			.append(" NOTSD.STATUS_ID ,  ")
			.append(" CASE WHEN NOTSD.STATUS_ID=21 THEN 'RECIEVED' WHEN NOTSD.STATUS_ID=22 THEN 'NOT RECIEVED' WHEN NOTSD.STATUS_ID=116 THEN 'APP NOT REGISTERED' END AS DELIVERED_STATUS,   ")
			.append(" CASE WHEN NOTSD.STATUS_ID=21 THEN NOTSD.DELIVERED_TIME WHEN NOTSD.STATUS_ID=22 THEN NULL END AS DELIVERED_TIME, NOTSD.VIEWED_TIME  AS VIEWED_TIME,D.DEVICE_MODEL  ")
			.append(" FROM NOTIFICATION NOTI   ")
			.append(" INNER JOIN NOTIFICATION_SENT_DETAILS NOTSD ON NOTSD.NOTIFICATION_ID=NOTI.ID   ")
			.append(" INNER JOIN FLAT_BOOKING FB ON FB.FLAT_ID=NOTSD.FLAT_ID   ")
			.append(" INNER JOIN CUSTOMER C ON FB.CUST_ID=C.CUST_ID   ")
			.append(" INNER JOIN FLAT F ON F.FLAT_ID=NOTSD.FLAT_ID   ")
			.append(" LEFT OUTER JOIN DEVICE D ON D.DEVICE_ID=NOTSD.DEVICE_ID   ")
			.append(" WHERE NOTSD.NOTIFICATION_ID=:NOTIFICATION_ID   ")
			.append(" AND FB.STATUS_ID=:STATUS_ID    ")
			.append(" AND C.STATUS_ID=:STATUS_ID  ")
			.toString();
	public static final String QRY_TO_INSERT_NOTIFICATION_BOOKING_DATES = new StringBuilder(" INSERT INTO ")
			.append(" NOTIFICATION_BOOKING_DATES ")
			.append(" (ID, ")
			.append(" TYPE_ID, ")
			.append(" TYPE_DATE, ")
			.append(" STATUS, ")
			.append(" CREATED_BY, ")
			.append(" CREATED_DATE) ")
			.append(" VALUES( ")
			.append(" NOTIFICATION_BOOKING_DATES_SEQ.NEXTVAL, ")
			.append(" :TYPE_ID, ")
			.append(" :TYPE_DATE, ")
			.append(" :STATUS, ")
			.append(" :CREATED_BY, ")
			.append(" SYSDATE) ")
			.toString();
	public static final String QRY_TO_GET_BOOKING_DATES = new StringBuilder(" SELECT ")
			.append(" NBD.TYPE_DATE,NBD.TYPE_ID   ")
			.append(" FROM NOTIFICATION_DETAIL_CHANGES NDC   ")
			.append(" INNER JOIN  NOTIFICATION_BOOKING_DATES NBD  ON(NBD.ID=NDC.ACTUAL)  ")
			.append(" WHERE NDC.NOTIFICATION_ID=:NOTIFICATION_ID AND NBD.STATUS=:STATUS  AND NDC.SEND_TYPE IN (108,109)  ")
			.toString();
	public static final String QRY_TO_GET_BOOKING_FLATS = new StringBuilder(" SELECT ")
			.append("  NDC.ACTUAL   ")
			.append("  FROM NOTIFICATION_DETAIL_CHANGES NDC ")
			.append("  WHERE NDC.NOTIFICATION_ID=:NOTIFICATION_ID AND NDC.STATUS=:STATUS AND NDC.SEND_TYPE=:SEND_TYPE ")
			.toString();
	public static final String INAACTIVE_DATE_IDS = new StringBuilder(" UPDATE ")
			.append("  NOTIFICATION_DETAIL_CHANGES   ")
			.append("  SET STATUS=:STATUS WHERE NOTIFICATION_ID=:NOTIFICATION_ID AND SEND_TYPE IN(:SEND_TYPE) ")
			.toString();
	public static final String INAACTIVATE_BOOKING_DATE_IDS = new StringBuilder(" UPDATE ")
			.append("  NOTIFICATION_BOOKING_DATES   ")
			.append("  SET STATUS=:STATUS WHERE ID IN (SELECT ACTUAL FROM NOTIFICATION_DETAIL_CHANGES WHERE NOTIFICATION_ID=:NOTIFICATION_ID AND SEND_TYPE IN(:SEND_TYPE)) ")
			.toString();
	public static final String QRY_TO_INSERT_MODIFIED_NOTIFICATION__DETAIL_CHANGES_FOR_DATE_IDS = new StringBuilder(" INSERT INTO ")
			.append(" NOTIFICATION_DETAIL_CHANGES ")
			.append(" (NOTIFICATION_DET_CHANGES_ID, ")
			.append(" SEND_TYPE, ")
			.append(" NOTIFICATION_ID, ")
			.append(" ACTUAL, ")
			.append(" MODIFIED_TO, ")
			.append(" STATUS, ")
			.append(" MODIFIED_BY, ")
			.append(" MODIFIED_DATE) ")
			.append(" VALUES( ")
			.append(" NOTIFICATION_DETAIL_CHANGES_SEQ.NEXTVAL, ")
			.append(" :SEND_TYPE, ")
			.append(" :NOTIFICATION_ID, ")
			.append(" :ACTUAL, ")
			.append(" :MODIFIED_TO, ")
			.append(" :STATUS, ")
			.append(" :MODIFIED_BY, ")
			.append(" SYSDATE) ")
			.toString();
	public static final String QRY_TO_GET_SITE_NAME_BY_SITE_ID = new StringBuilder(" SELECT ")
			.append(" SITE.NAME AS SITE_NAME,SITE.IMAGE_LOCATION  ")
			.append(" FROM  ")
			.append(" SITE SITE  ")
			.append(" WHERE SITE.SITE_ID=:SITE_ID ")
			.toString();
	public static final String QRY_TO_GET_DATE = new StringBuilder(" SELECT ")
			.append(" TYPE_DATE  ")
			.append(" FROM  ")
			.append(" NOTIFICATION_BOOKING_DATES WHERE ID IN(:ID) AND STATUS=:STATUS ")
			.toString();
	
	public static final String QRY_TO_GET_FLAT_NO = new StringBuilder(" SELECT ")
			.append("  FLAT_NO   ")
			.append("  FROM FLAT ")
			.append(" WHERE FLAT_ID IN(:FLAT_ID) AND STATUS_ID=:STATUS_ID ")
			.toString();
}